limit_req_zone $binary_remote_addr zone=mylimit:10m rate=2r/s;

server {
    listen 80;

    # Dạy Nginx: Gặp lỗi 403 thì mở file 403, gặp lỗi 401 thì mở file captcha
    error_page 403 = /403.html;
    error_page 401 = /captcha.html;

    if ($request_uri ~* "(<script|%3Cscript|/etc/passwd|\.\./\.\.)") {
        return 403;
    }

    location / {
        limit_req zone=mylimit burst=5 nodelay;
        auth_request /auth;
        
        # Bắt buộc phải có dòng này để Nginx chịu chuyển hướng lỗi của API sang trang HTML
        proxy_intercept_errors on; 
        
        proxy_pass http://backend:80;
    }

    # API giải mã CAPTCHA của Backend
    location /solve-captcha {
        proxy_pass http://security_api:5000/solve-captcha;
    }

    location = /auth {
        internal;
        proxy_pass http://security_api:5000/verify;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header X-Original-URI $request_uri; 
        proxy_set_header X-Real-IP $remote_addr;
    }

    location = /403.html {
        default_type text/html;
        return 403 "<h1 style='color:red'>403 Forbidden</h1><p>Bi chan boi Gateway (AI hoac WAF Rule).</p>";
    }

    # Chỉ đường cho Nginx đọc file captcha.html
    location = /captcha.html {
        root /usr/share/nginx/html;
        internal;
    }
}